version: "3"

services:
  db:
    image: postgres:16.2
    container_name: "turbo-ecom-db"
    restart: always
    environment:
      POSTGRES_USER: next-turbo
      POSTGRES_PASSWORD: next-turbo
      POSTGRES_DB: next-turbo
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
