import {
  Activity,
  AlertTriangle,
  Bell,
  Book,
  Bot,
  Calendar,
  Camera,
  CandlestickChart,
  Check,
  Clock,
  Cog,
  Copy,
  CreditCard,
  Eye,
  FileClock,
  Fingerprint,
  Globe2,
  Hammer,
  Hourglass,
  Image,
  KeyRound,
  Laptop,
  LayoutDashboard,
  LineChart,
  Link,
  Linkedin,
  Megaphone,
  MessageCircle,
  Minus,
  Moon,
  Newspaper,
  PanelTop,
  Pencil,
  Play,
  Plug,
  Puzzle,
  Ratio,
  Search,
  SearchCheck,
  Siren,
  Sparkles,
  SunMedium,
  Table,
  Tag,
  Timer,
  ToyBrick,
  Trash,
  TwitterIcon,
  UserCircle,
  Users,
  Webhook,
  Youtube,
  Zap,
} from "lucide-react";
import type { LucideIcon, LucideProps } from "lucide-react";

export type Icon = LucideIcon;
export type ValidIcon = keyof typeof Icons;

export const Icons = {
  activity: Activity,
  "layout-dashboard": LayoutDashboard,
  link: Link,
  siren: Siren,
  "panel-top": PanelTop,
  table: Table,
  "toy-brick": ToyBrick,
  cog: Cog,
  hammer: Hammer,
  search: Search,
  "search-check": SearchCheck,
  fingerprint: Fingerprint,
  pencil: Pencil,
  "message-circle": MessageCircle,
  calendar: Calendar,
  tag: Tag,
  trash: Trash,
  twitter: TwitterIcon,
  globe: Globe2,
  plug: Plug,
  copy: Copy,
  check: Check,
  play: Play,
  bot: Bot,
  puzzle: Puzzle,
  image: Image,
  bell: Bell,
  zap: Zap,
  eye: Eye,
  users: Users,
  key: KeyRound,
  "credit-card": CreditCard,
  "alert-triangle": AlertTriangle,
  "file-clock": FileClock,
  megaphone: Megaphone,
  webhook: Webhook,
  minus: Minus,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  sparkles: Sparkles,
  timer: Timer,
  clock: Clock,
  "line-chart": LineChart,
  linkedin: Linkedin,
  book: Book,
  newspaper: Newspaper,
  youtube: Youtube,
  "hour-glass": Hourglass,
  "candlestick-chart": CandlestickChart,
  ratio: Ratio,
  user: UserCircle,
  camera: Camera,
} as const;
